### ISSUE TITLE
Solve failed

### ISSUE THREAD

**Issue by unktomi** [Kinect/RoomAliveToolkit#14]
decoding Gray code images for projector 0, camera 0
elapsed time 1588
projecting depth points to color camera 0
rejected 14.13666% pixels for high variance
elapsed time 1770
projector 0 is seen by camera 0 (20180 points)
elapsed time 1858
calibrating projector 0
RANSAC iteration 0
error = 429.497279415675
RANSAC iteration 1
error = 151.60088993423
RANSAC iteration 2
error = 116.755996115679
RANSAC iteration 3
error = 114.391513594397
RANSAC iteration 4
error = 93.634629536181
RANSAC iteration 5
error = 79.4883445206181
RANSAC iteration 6
error = 97.0091158968851
RANSAC iteration 7
error = 77.5354579378281
RANSAC iteration 8
error = 71.8200025854655
RANSAC iteration 9
error = 60.2050934296484
Solve failed
RoomAliveToolkit.ProjectorCameraEnsemble+CalibrationFailedException: Unable to successfully calibrate projector: 0
   at RoomAliveToolkit.ProjectorCameraEnsemble.CalibrateProjectorGroups(String directory) in E:\GitHub\RoomAliveToolkit\ProCamCalibration\ProCamEnsembleCalibration\ProjectorCameraEnsemble.cs:line 668
   at RoomAliveToolkit.MainForm.Solve() in E:\GitHub\RoomAliveToolkit\ProCamCalibration\CalibrateEnsemble\MainForm.cs:line 1115
Solve complete

Any ideas? 

Thanks!

**Comment by thundercarrot** [comment]
Can you zip up your calibration directory and put it some place where I can download it? Thanks

Sent from my Windows Phone
________________________________

**Comment by devevderyadav** [comment]
Hi  I am also facing the  exact same  issue , @unktomi were u able to find out the solution ? 

@thundercarrot  when I started the calibration I could calibrate for first time correctly but  now when i am trying to calibrate again for new location  it shows the above error message .....

Thanks in advance _/\_

Regards
Devender

**Comment by thundercarrot** [comment]
Devender, can you zip up your calibration directory and put it some place where I can download it? Thanks

**Comment by devevderyadav** [comment]
@thundercarrot  I solved this by choosing some other locationing for calibration which has more depth  and  3D view.   but I still wonder how come I was able to calibrate first time at the same place but not after that.

**Comment by devevderyadav** [comment]
Hi @thundercarrot 

I got this Solve failed error again , I  downloaded the fresh code from git  & just compiled it without any modification. I am attaching the image of error message. (One kinect one projector)
![error1](https://cloud.githubusercontent.com/assets/3774356/12063325/ef7cbb82-afd2-11e5-898f-21cc255ed0d0.png)

Thanks
Devender

**Comment by thundercarrot** [comment]
Try making the projected image larger -- i.e. move the projector back.

Can you zip up your calibration directory and put it some place where I can download it? I will take a look.

**Comment by devevderyadav** [comment]
Hi Andy ,

  Yes, by making projected  image larger the error disappeared! I wasted 2 days resolving such a silly thing (I was debugging code ) but than your comment came as a New Year GIFT :smile:  Thank u so much

Happy New Year!
Devender

**Comment by sapratte** [comment]
Hi,

I'm also getting the solve failed error: 
Solve failed
RoomAliveToolkit.ProjectorCameraEnsemble+CalibrationFailedException: Unable to successfully calibrate projector: 0

Here is my calibration directory:

https://www.dropbox.com/s/1q3ou58lvb4dmx1/Calibration.zip?dl=0

Thanks!

**Comment by thundercarrot** [comment]
Sapratte,

The projected image as seen by the camera is too small. Try moving camera closer.

Also, your projection surface is too flat for the calibration to recover projector intrinsics. Try shooting into a corner or temporarily place some large objects like a box in the scene.

**Comment by sapratte** [comment]
Hi Andy,

Thanks for the fast response! I got the projector and camera calibrated and
I think I have successfully run the sample project.

However I am now at a loss as to how to proceed. I believe you spoke to a
friend of mine, Teddy Seyed about the device communication toolkit (Society
of Devices Toolkit) we've been working on at the University of Calgary. I
want to make a simple map application that links the projected display to a
physical display. Could you give me some tips on how to get started on
linking the RoomAlive toolkit to another application?

Sorry to bother you with this, I just thought it would be faster to get
your help right away.

Thanks,
Sydney

**Comment by thundercarrot** [comment]
Sydney,

I'm not sure I understand what you're trying to do, but I'll go after "linking the RoomAlive toolkit to another application". You have a couple of options. First, if you have the source code for the application, you could wire it into the ProjectionMappingSample directly. If you do not, your second option is to look at the "desktop duplication" feature of the ProjectionMappingSample, where any application that renders to the Windows desktop can be used as the target view for projection mapping.
