### ISSUE TITLE
Exception on Acquire

### ISSUE THREAD

**Issue by unktomi** [Kinect/RoomAliveToolkit#26]
Loaded E:\project\calibrate.xml
Acquire failed
System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Index was outside the bounds of the array. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RoomAliveToolkit.ProjectorServer.Size(Int32 screenIndex) in e:\GitHub\RoomAliveToolkit\ProCamCalibration\ProjectorServer\ProjectorServer.cs:line 43
   at SyncInvokeSize(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)).
Acquire complete

**Comment by thundercarrot** [comment]
Can you double check that the display index values used in your .xml file agree with what is available on the system? CalibrateEnsemble includes a "Show Projector Server Connected Displays" option on the Setup menu that can be useful here.
